import { Group, Meetup, SponsorBanner, LocationData, Report, User, SocialTrend } from '@/types';

export const CURRENT_USER: User = {
  id: 'a0000000-0000-0000-0000-000000000001',
  email: 'prayag129787@gmail.com',
  display_name: 'Prayag Bagtharia',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  interest_tags: ['Tech', 'Startups', 'Food & Dining', 'Fitness', 'Photography'],
  is_verified: true,
  is_founding_member: true,
  college_email_badge: true,
  role: 'admin',
  city: 'Surat',
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'g-tech-surat',
    name: 'Surat Tech & Startup Circle',
    description: 'Connect with founders, engineers, and creators in Surat. We host monthly tech mixers, demo days, and peer learning sessions across Vesu & Piplod.',
    category: 'Custom',
    is_public: true,
    admin_id: 'a0000000-0000-0000-0000-000000000001',
    admin_name: 'Prayag B.',
    cover_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    rules: '1. No sales spam or uninvited DM solicitations\n2. Share genuine learnings & open source projects\n3. Respect community members',
    member_count: 1,
    max_members: 256,
    require_approval: false,
    only_admins_message: false,
    invite_code: 'cc_surat_tech_829',
    invite_link_enabled: true,
    verified_only: false,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'g-trekkers',
    name: 'Weekend Trekkers & Explorers',
    description: 'Discover scenic trails, weekend getaways, waterfalls, and outdoor sunrise rides around Surat, Dumas, and Dang forests.',
    category: 'Tourism',
    is_public: true,
    admin_id: 'a0000000-0000-0000-0000-000000000002',
    admin_name: 'Aarav M.',
    cover_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    rules: '1. Safety first: helmet and hydration mandatory\n2. Leave no trace / zero littering\n3. Coordinate carpooling in group chat',
    member_count: 1,
    max_members: 150,
    require_approval: false,
    only_admins_message: false,
    invite_code: 'cc_surat_treks_104',
    invite_link_enabled: true,
    verified_only: false,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'g-foodies',
    name: 'Surat Foodies & Cafes Club',
    description: 'Exploring the legendary street food and aesthetic specialty coffee cafes in Surat, from Dumas Road to Vesu and Ghod Dod.',
    category: 'Party',
    is_public: true,
    admin_id: 'a0000000-0000-0000-0000-000000000003',
    admin_name: 'Diya P.',
    cover_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    rules: '1. Real food reviews only\n2. Mention veg/jain friendly options for group dinners\n3. Split bills equally via UPI at venues',
    member_count: 1,
    max_members: 256,
    require_approval: false,
    only_admins_message: false,
    invite_code: 'cc_surat_food_991',
    invite_link_enabled: true,
    verified_only: false,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'g-svnit',
    name: 'SVNIT & University Alumni Network',
    description: 'Students and alumni from SVNIT and Surat universities networking, mentoring, building side projects, and sharing career referrals.',
    category: 'University',
    is_public: true,
    admin_id: 'a0000000-0000-0000-0000-000000000004',
    admin_name: 'Rohan K.',
    cover_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    rules: '1. Verified college email gets an alumni badge\n2. Constructive mentorship discussions only\n3. Post job referrals in designated threads',
    member_count: 1,
    max_members: 500,
    require_approval: true,
    only_admins_message: false,
    invite_code: 'cc_svnit_alumni_442',
    invite_link_enabled: true,
    verified_only: true,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'g-property',
    name: 'Surat Commercial & Living Spaces',
    description: 'Trusted peer discussions on flatmate matching, co-working spaces, rental flats in Vesu/Pal, and verified commercial property reviews.',
    category: 'Property',
    is_public: false,
    admin_id: 'a0000000-0000-0000-0000-000000000005',
    admin_name: 'Meera S.',
    cover_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    rules: '1. Admin approval required to join\n2. Direct owner and verified listings only\n3. No brokerage spam without prior disclosure',
    member_count: 1,
    max_members: 100,
    require_approval: true,
    only_admins_message: true,
    invite_code: 'cc_surat_prop_518',
    invite_link_enabled: false,
    verified_only: true,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MEETUPS: Meetup[] = [
  {
    id: 'm-ai-mixer',
    title: 'Surat AI & Fullstack Developers Mixer',
    description: 'Casual evening meetup discussing Next.js 16, Supabase, LLM integrations, and local Surat tech startups. Refreshments provided!',
    place: 'The House of Caffeine, Vesu Main Road, Surat',
    latitude: 21.1418,
    longitude: 72.7756,
    date_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    group_id: 'g-tech-surat',
    group_name: 'Surat Tech & Startup Circle',
    category: 'Custom',
    capacity: 35,
    rsvps_count: 0,
    ticket_price: 0,
    created_by: 'a0000000-0000-0000-0000-000000000001',
    creator_name: 'Prayag B.',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'm-cycling-dumas',
    title: 'Sunrise Cycling & Breakfast at Dumas Beach',
    description: 'Early morning 18km leisurely cycle ride starting from SVNIT circle along Dumas highway, ending with local chai, poha and beach breeze.',
    place: 'SVNIT Main Gate, Ichchhanath, Surat',
    latitude: 21.1645,
    longitude: 72.7845,
    date_time: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
    group_id: 'g-trekkers',
    group_name: 'Weekend Trekkers & Explorers',
    category: 'Tourism',
    capacity: 25,
    rsvps_count: 0,
    ticket_price: 0,
    created_by: 'a0000000-0000-0000-0000-000000000002',
    creator_name: 'Aarav M.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'm-cafe-crawl',
    title: 'Weekend Artisanal Coffee & Dessert Tasting',
    description: 'Join fellow coffee enthusiasts for a 3-stop cafe crawl tasting specialty pour-overs, cold brews, and fresh bakes around Piplod.',
    place: 'Nomad Coffee Co, VIP Road, Vesu, Surat',
    latitude: 21.1523,
    longitude: 72.7812,
    date_time: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    group_id: 'g-foodies',
    group_name: 'Surat Foodies & Cafes Club',
    category: 'Party',
    capacity: 15,
    rsvps_count: 0,
    ticket_price: 150,
    created_by: 'a0000000-0000-0000-0000-000000000003',
    creator_name: 'Diya P.',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_SPONSOR_BANNERS: SponsorBanner[] = [
  {
    id: 'sp-1',
    sponsor_id: 'sp-caffeine',
    sponsor_name: 'The House of Caffeine',
    placement: 'group',
    target_id: 'g-tech-surat',
    title: 'Official Coworking Partner',
    description: 'Enjoy 15% off specialty coffee & free high-speed WiFi for CityCircle verified members.',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
    link_url: 'https://instagram.com',
    start_date: new Date().toISOString(),
    end_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'sp-2',
    sponsor_id: 'sp-surathub',
    sponsor_name: 'Surat Innovation Hub',
    placement: 'global',
    title: 'Surat Startup Weekend 2026',
    description: 'Pitch your idea to angel investors. Registrations now open for verified members.',
    image_url: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=600&q=80',
    link_url: 'https://suratstartup.org',
    start_date: new Date().toISOString(),
    end_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_FUZZED_PEOPLE: LocationData[] = [];

export const INITIAL_REPORTS: Report[] = [];

export const INITIAL_SURAT_TRENDS: SocialTrend[] = [
  {
    id: 'trend-ig-1',
    platform: 'instagram',
    title: '5 Hidden Aesthetic Cafes in Vesu That Offer Good Wi-Fi & Specialty Pour-Overs ☕✨',
    content: 'Tired of overcrowded Starbucks? We mapped out the top 5 quietest work cafes in Vesu & Piplod with high-speed WiFi, artisanal brews, and quiet corners for remote founders. Bookmark for your next productive afternoon!',
    author_name: 'Surat Food & Places',
    author_handle: '@surat_foodexplorer',
    author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://instagram.com/p/surat_cafes_vesu',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    hashtags: ['#suratfood', '#suratcafes', '#vesu', '#workfromsurat', '#coffeelovers'],
    category: 'Food & Cafes',
    likes_count: 1420,
    comments_count: 88,
    posted_at: '2 hours ago',
    is_verified_creator: true,
    neighborhood: 'Vesu Main Road, Surat',
    aspect_ratio: 'portrait',
  },
  {
    id: 'trend-reddit-1',
    platform: 'reddit',
    title: '[r/surat] The Ultimate Locho Debate: Adajan Jaani vs Vesu Gopal Locho vs Nanpura — Where is the truest Oil/Butter ratio?',
    content: 'Been in Surat for 10 years now. There is always a heated war between Adajan Jaani Locho loyalists and Nanpura originals. Can we settle this once and for all? What is your holy grail Locho order with sev and green chutney?',
    author_name: 'u/surti_foodie_99',
    author_handle: 'u/surti_foodie_99',
    author_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://reddit.com/r/surat/comments/locho_debate',
    subreddit: 'r/surat',
    category: 'Food & Cafes',
    likes_count: 342,
    upvotes_count: 342,
    comments_count: 154,
    posted_at: '4 hours ago',
    neighborhood: 'Adajan & Nanpura, Surat',
  },
  {
    id: 'trend-ig-2',
    platform: 'instagram',
    title: 'Surat Diamond Bourse at Night: Drone Shot of the World’s Largest Office Building 💎✨',
    content: 'Capturing the golden hour transition at Khajod DREAM City. Surat Diamond Bourse looking majestic with over 4,500 diamond offices under one roof. Surat is truly going global!',
    author_name: 'Surat Drone Captures',
    author_handle: '@surat_aerials',
    author_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://instagram.com/p/surat_sdb_drone',
    image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    hashtags: ['#suratdiamondbourse', '#khajod', '#suratcity', '#dronestagram', '#gujarat'],
    category: 'Civic & Infrastructure',
    likes_count: 3890,
    comments_count: 210,
    posted_at: '6 hours ago',
    is_verified_creator: true,
    neighborhood: 'DREAM City Khajod, Surat',
    aspect_ratio: 'square',
  },
  {
    id: 'trend-reddit-2',
    platform: 'reddit',
    title: '[r/surat] Surat Metro Phase 1: Pillar work completed along Dumas-Airport corridor! When can we expect commercial trial runs?',
    content: 'Passed by Surat Airport road yesterday and noticed the elevated track viaducts look almost connected near Althan and VIP Road junction. Anyone with SMC / GMRC engineering inside insights on expected passenger trial dates for 2026?',
    author_name: 'u/infra_watcher_guj',
    author_handle: 'u/infra_watcher_guj',
    author_avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://reddit.com/r/surat/comments/surat_metro_phase1_updates',
    subreddit: 'r/surat',
    category: 'Civic & Infrastructure',
    likes_count: 215,
    upvotes_count: 215,
    comments_count: 67,
    posted_at: '7 hours ago',
    neighborhood: 'Dumas Road & VIP Junction',
  },
  {
    id: 'trend-ig-3',
    platform: 'instagram',
    title: 'Surat Tech Community Meetup #14 Recap! AI Agents, Next.js & Local Founder Pitches 🚀💡',
    content: 'Over 85 developers and indie hackers gathered at Piplod this Saturday! From building offline-first local apps to scaling Supabase real-time instances. Surat’s tech ecosystem is leveling up fast!',
    author_name: 'Surat Techies',
    author_handle: '@surat_techies',
    author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://instagram.com/p/surat_tech_recap',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    hashtags: ['#surattech', '#startupsurat', '#svnit', '#piplod', '#indiemaker'],
    category: 'Tech & Startups',
    likes_count: 875,
    comments_count: 42,
    posted_at: '12 hours ago',
    is_verified_creator: true,
    neighborhood: 'Piplod, Surat',
    aspect_ratio: 'landscape',
  },
  {
    id: 'trend-reddit-3',
    platform: 'reddit',
    title: '[r/surat] Best weekend cycling routes before 7:00 AM? Sharing my favorite 25km loop from SVNIT to Dumas Beach.',
    content: 'For all morning cyclists in Surat: Start SVNIT Gate -> Gaurav Path -> VIP Circle -> Dumas Coastline -> Back via Piplod Canal Road. Zero traffic, cool breeze, and fresh coconut water at the end. Who wants to join a Saturday 5:30 AM group ride?',
    author_name: 'u/pedal_surat',
    author_handle: 'u/pedal_surat',
    author_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://reddit.com/r/surat/comments/cycling_routes_dumas',
    subreddit: 'r/surat',
    category: 'Culture & Gems',
    likes_count: 189,
    upvotes_count: 189,
    comments_count: 38,
    posted_at: '18 hours ago',
    neighborhood: 'SVNIT to Dumas Road',
  },
  {
    id: 'trend-ig-4',
    platform: 'instagram',
    title: 'Surat Night Market at Pal: Cold Coco, Live Gazals, & Handcrafted Gujarati Street Food 🌙🍧',
    content: 'There’s no vibe like post-10 PM Surat! Check out our reel guide to the late-night Pal Food Street with live acoustic performances, spicy Sev Khamani, and iconic A-One Cold Coco.',
    author_name: 'Surat After Dark',
    author_handle: '@surat_nightlife',
    author_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://instagram.com/p/surat_night_pal',
    image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    hashtags: ['#suratnightlife', '#coldcoco', '#pal', '#suratstreetfood', '#suratdiaries'],
    category: 'Events & Nightlife',
    likes_count: 2450,
    comments_count: 135,
    posted_at: '1 day ago',
    is_verified_creator: true,
    neighborhood: 'Pal & Adajan, Surat',
    aspect_ratio: 'portrait',
  },
  {
    id: 'trend-reddit-4',
    platform: 'reddit',
    title: '[r/gujarat] Why Surat continues to rank #1 as India’s cleanest big city: Insights from civic sanitation workers & SMC smart dashboard',
    content: 'A deep dive into Surat Municipal Corporation’s automated garbage transfer monitoring, door-to-door segregation metrics, and the citizen feedback loops that keep our neighborhoods pristine.',
    author_name: 'u/smart_city_guj',
    author_handle: 'u/smart_city_guj',
    author_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    source_url: 'https://reddit.com/r/gujarat/comments/surat_cleanest_city',
    subreddit: 'r/gujarat',
    category: 'Civic & Infrastructure',
    likes_count: 420,
    upvotes_count: 420,
    comments_count: 91,
    posted_at: '1 day ago',
    neighborhood: 'Surat Municipal Limits',
  },
];

